const canvas=document.getElementById('pongCanvas'),ctx=canvas.getContext('2d');
const menu=document.getElementById('menu'),game=document.getElementById('game'),gameOver=document.getElementById('gameOver'),pauseOverlay=document.getElementById('pauseOverlay'),statusEl=document.getElementById('status');
let difficulty='normal',targetScore=5,running=false,paused=false,playerScore=0,aiScore=0,rally=0,bestRally=0,pointsWon=0,stage=1,soundOn=true,musicOn=true,audioCtx,musicTimer;
const keys={},player={x:22,y:210,w:12,h:80,speed:8},ai={x:canvas.width-34,y:210,w:12,h:80,speed:5.2},ball={x:450,y:250,r:8,vx:5,vy:2.5,maxSpeed:15};let pointerY=250;
const stages=[{name:'NEON DRIVE',tempo:120,notes:[220,277,330,440]},{name:'CYBER RUSH',tempo:140,notes:[196,247,294,392]},{name:'LASER STORM',tempo:158,notes:[165,220,277,330]},{name:'FINAL OVERDRIVE',tempo:176,notes:[147,196,247,294]}];
const highScore=()=>Number(localStorage.getItem('neonPongHighScore')||0),winStreak=()=>Number(localStorage.getItem('neonPongWinStreak')||0);
function audio(){try{audioCtx||=new(window.AudioContext||window.webkitAudioContext)();if(audioCtx.state==='suspended')audioCtx.resume();return true}catch(e){return false}}
function beep(freq=440,d=.05){if(!soundOn||!audio())return;const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.frequency.value=freq;g.gain.value=.035;o.connect(g);g.connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+d)}
function musicStart(){if(!musicOn||!audio())return;clearInterval(musicTimer);let i=0;const play=()=>{if(!running||paused||!musicOn)return;const s=stages[stage-1],o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type=stage===1?'triangle':stage===2?'square':stage===3?'sawtooth':'sine';o.frequency.value=s.notes[i++%s.notes.length];g.gain.setValueAtTime(.018,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.001,audioCtx.currentTime+.22);o.connect(g);g.connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+.24)};play();musicTimer=setInterval(play,60000/stages[stage-1].tempo)}
function musicStop(){clearInterval(musicTimer)}
function updateStage(){const old=stage;stage=rally>=21?4:rally>=13?3:rally>=6?2:1;document.getElementById('stageName').textContent=`STAGE ${stage}`;document.getElementById('stageDisplay').textContent=stages[stage-1].name;document.getElementById('stageProgress').style.width=`${Math.min(100,(rally%7)/6*100)}%`;if(stage!==old){statusEl.textContent=`STAGE ${stage}!`;flash();beep(980,.18);musicStart()}}
function flash(){const f=document.getElementById('flash');f.classList.remove('show');void f.offsetWidth;f.classList.add('show')}
function resetBall(dir=Math.random()>.5?1:-1){ball.x=450;ball.y=250;ball.vx=dir*5;ball.vy=(Math.random()-.5)*5;rally=0;updateStage()}
function resetMatch(){playerScore=aiScore=pointsWon=bestRally=rally=0;stage=1;player.y=ai.y=210;resetBall();updateScore()}
function updateScore(){document.getElementById('playerScore').textContent=playerScore;document.getElementById('aiScore').textContent=aiScore;document.getElementById('targetDisplay').textContent=targetScore}
function clamp(){player.y=Math.max(0,Math.min(420,player.y));ai.y=Math.max(0,Math.min(420,ai.y))}
function updatePlayer(){if(keys.ArrowUp||keys.w||keys.W)player.y-=player.speed;if(keys.ArrowDown||keys.s||keys.S)player.y+=player.speed;const t=pointerY-40;if(Math.abs(pointerY-250)>8)player.y+=(t-player.y)*.16}
function updateAI(){const [speed,margin]={easy:[3.6,55],normal:[5.2,28],hard:[7.2,10]}[difficulty],c=ai.y+40;if(c<ball.y-margin)ai.y+=speed;else if(c>ball.y+margin)ai.y-=speed}
function paddleHit(p){return ball.x-ball.r<p.x+p.w&&ball.x+ball.r>p.x&&ball.y>p.y&&ball.y<p.y+p.h}
function hitPaddle(p,dir){const rel=(ball.y-(p.y+40))/40,s=Math.min(Math.hypot(ball.vx,ball.vy)*1.055,ball.maxSpeed);ball.vx=dir*Math.sqrt(Math.max(16,s*s-(rel*s*.9)**2));ball.vy=rel*s*.9;ball.x=dir>0?p.x+p.w+ball.r:p.x-ball.r;rally++;bestRally=Math.max(bestRally,rally);updateStage();beep(620+Math.min(rally*12,300),.035)}
function scorePoint(side){if(side==='player'){playerScore++;pointsWon++;beep(880,.12)}else{aiScore++;beep(180,.12)}flash();updateScore();if(playerScore>=targetScore||aiScore>=targetScore)return finishMatch();statusEl.textContent=side==='player'?'POINT PLAYER':'POINT AI';resetBall(side==='player'?1:-1);musicStart()}
function updateBall(){ball.x+=ball.vx;ball.y+=ball.vy;if(ball.y-ball.r<=0||ball.y+ball.r>=500){ball.vy*=-1;ball.y=Math.max(ball.r,Math.min(500-ball.r,ball.y));beep(300,.025)}if(ball.vx<0&&paddleHit(player))hitPaddle(player,1);if(ball.vx>0&&paddleHit(ai))hitPaddle(ai,-1);if(ball.x<-ball.r)scorePoint('ai');if(ball.x>900+ball.r)scorePoint('player')}
function draw(){ctx.fillStyle='#05070d';ctx.fillRect(0,0,900,500);ctx.strokeStyle='rgba(255,255,255,.13)';ctx.setLineDash([12,14]);ctx.beginPath();ctx.moveTo(450,0);ctx.lineTo(450,500);ctx.stroke();ctx.setLineDash([]);ctx.shadowBlur=18;ctx.fillStyle='#63ffda';ctx.shadowColor='#63ffda';ctx.fillRect(player.x,player.y,player.w,player.h);ctx.fillStyle='#ff5c8a';ctx.shadowColor='#ff5c8a';ctx.fillRect(ai.x,ai.y,ai.w,ai.h);ctx.fillStyle='#fff';ctx.shadowColor='#fff';ctx.beginPath();ctx.arc(ball.x,ball.y,ball.r,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;for(let i=0;i<stage;i++){ctx.globalAlpha=.12;ctx.fillStyle=i%2?'#ff5c8a':'#63ffda';ctx.beginPath();ctx.arc(450,250,80+i*45,0,Math.PI*2);ctx.stroke();ctx.globalAlpha=1}}
function loop(){if(running&&!paused){updatePlayer();updateAI();clamp();updateBall()}draw();requestAnimationFrame(loop)}
function startGame(){menu.classList.add('hidden');gameOver.classList.add('hidden');game.classList.remove('hidden');resetMatch();running=true;paused=false;pauseOverlay.classList.add('hidden');statusEl.textContent='FIGHT!';audio();musicStart()}
function finishMatch(){running=false;musicStop();game.classList.add('hidden');gameOver.classList.remove('hidden');const won=playerScore>aiScore;if(won)localStorage.setItem('neonPongWinStreak',winStreak()+1);else localStorage.setItem('neonPongWinStreak','0');const hs=Math.max(highScore(),playerScore);localStorage.setItem('neonPongHighScore',hs);document.getElementById('winnerText').textContent=won?'PLAYER WINS':'AI WINS';document.getElementById('finalScore').textContent=`${playerScore} — ${aiScore}`;document.getElementById('rallyStat').textContent=bestRally;document.getElementById('pointsStat').textContent=pointsWon;document.getElementById('highScoreStat').textContent=hs;document.getElementById('streakStat').textContent=winStreak()}
function togglePause(){if(!running)return;paused=!paused;pauseOverlay.classList.toggle('hidden',!paused);statusEl.textContent=paused?'PAUSED':'FIGHT!';paused?musicStop():musicStart()}
window.addEventListener('keydown',e=>{keys[e.key]=true;if(['ArrowUp','ArrowDown',' '].includes(e.key))e.preventDefault();if(e.key.toLowerCase()==='p')togglePause()});window.addEventListener('keyup',e=>keys[e.key]=false);
function setPointer(e){const r=canvas.getBoundingClientRect();pointerY=(e.clientY-r.top)*(500/r.height)}canvas.addEventListener('mousemove',setPointer);canvas.addEventListener('touchmove',e=>{e.preventDefault();setPointer(e.touches[0])},{passive:false});canvas.addEventListener('pointerdown',e=>{setPointer(e);audio()});
for(const b of document.querySelectorAll('.mode-btn'))b.onclick=()=>{document.querySelectorAll('.mode-btn').forEach(x=>x.classList.remove('active'));b.classList.add('active');difficulty=b.dataset.difficulty};for(const b of document.querySelectorAll('.target-btn'))b.onclick=()=>{document.querySelectorAll('.target-btn').forEach(x=>x.classList.remove('active'));b.classList.add('active');targetScore=Number(b.dataset.target)};
document.getElementById('startBtn').onclick=startGame;document.getElementById('rematchBtn').onclick=startGame;document.getElementById('menuBtn').onclick=()=>{gameOver.classList.add('hidden');menu.classList.remove('hidden')};document.getElementById('quitBtn').onclick=()=>{running=false;musicStop();game.classList.add('hidden');menu.classList.remove('hidden')};document.getElementById('pauseBtn').onclick=togglePause;
document.getElementById('soundBtn').onclick=e=>{soundOn=!soundOn;e.currentTarget.textContent=soundOn?'🔊':'🔇'};document.getElementById('musicBtn').onclick=e=>{musicOn=!musicOn;e.currentTarget.textContent=musicOn?'♫':'×';if(musicOn&&running&&!paused)musicStart();else musicStop()};
updateScore();updateStage();draw();loop();
